[general]
import = [
  "C:\\Users\\Isaque Diniz\\AppData\\Roaming\\alacritty\\themes\\gruvbox_material_medium_dark.toml"
  ##"~/.config/alacritty/themes/gruvbox_material_medium_dark.toml" -> MacOS
]
live_config_reload = true

[env]
TERM="xterm-256color"

## Only for WSL
#[shell]
#program = "ubuntu"

[window]
decorations = "None"
# MacOS -> decorations = "Transparent"
# MacOS -> startup_mode = "Windowed"
padding = { x = 10, y = 10 }
dynamic_padding = true
dimensions = { columns = 150, lines = 40 }
position = { x = 0, y = 0 }

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }
size = 14

[cursor]
style = { shape = "Beam", blinking = "On" }

[selection]
save_to_clipboard = true
